import React from "react";
import { useState } from "react";

const MenuDropdown = () => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="flex justify-center my-auto lg:hidden">
      <div>
        <div className="dropend relative">
          <button
            className="
          dropdown-toggle
          px-6
          py-2.5
          bg-black
          text-white
          font-medium
          text-xs
          leading-tight
          uppercase
          rounded
          shadow-md
          hover:bg-gray-800 hover:shadow-lg
          focus:bg-gray-800 focus:shadow-lg focus:outline-none focus:ring-0
          active:bg-gray-800 active:shadow-lg active:text-white
          transition
          duration-150
          ease-in-out
          flex
          items-center
          whitespace-nowrap
        "
            type="button"
            id="dropdownMenuButton1e"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            onClick={() => (isOpen ? setIsOpen(false) : setIsOpen(true))}
          >
            MENÚ
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="currentColor"
              className="bi bi-list"
              viewBox="0 0 16 16"
            >
              <path
                fill-rule="evenodd"
                d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"
              />
            </svg>
          </button>
          <ul
            className={`
          dropdown-menu
          min-w-max
          absolute
          ${isOpen ? "block" : "hidden"}
          bg-black
          text-base
          z-50
          float-left
          py-2
          list-none
          text-left
          rounded-lg
          shadow-lg
          mt-1
          m-0
          bg-clip-padding
          border-none
        `}
            aria-labelledby="dropdownMenuButton1e"
          >
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-white
              hover:bg-white
              hover:text-black
            "
                href="/"
              >
                INICIO
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-white
              hover:bg-white
              hover:text-black
            "
                href="/nosotros"
              >
                NOSOTROS
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-white
              hover:bg-white
              hover:text-black
            "
                href="/horarios"
              >
                HORARIOS
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-white
              hover:bg-white
              hover:text-black
            "
                href="/equipo"
              >
                EQUIPO
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-white
              hover:bg-white
              hover:text-black
            "
                href="/servicios"
              >
                SERVICIOS
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-white
              hover:bg-white
              hover:text-black
            "
                href="/galeria"
              >
                GALERÍA
              </a>
            </li>
            <li>
              <a
                className="
              dropdown-item
              text-sm
              py-2
              px-4
              font-normal
              block
              w-full
              whitespace-nowrap
              bg-transparent
              text-white
              hover:bg-white
              hover:text-black
            "
                href="/contaco"
              >
                CONTACTO
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default MenuDropdown;
